// Estados de COMPROBANTES
export enum EstadoEnumComprobante {
  PENDIENTE = 'PENDIENTE',
  ACEPTADO = 'ACEPTADO',
  RECHAZADO = 'RECHAZADO',
  OBSERVADO = 'OBSERVADO',
  POR_RECTIFICAR = 'POR_RECTIFICAR',
  ANULADO = 'ANULADO',
  CONTINGENCIA = 'CONTINGENCIA',
  ERROR = 'ERROR',
}

// Estados de RESUMEN DE BOLETAS
export enum EstadoEnumResumen {
  PENDIENTE = 'PENDIENTE',
  ENVIADO = 'ENVIADO',
  ACEPTADO = 'ACEPTADO',
  RECHAZADO = 'RECHAZADO',
  POR_RECTIFICAR = 'POR_RECTIFICAR',
  CONTINGENCIA = 'CONTINGENCIA',
  ERROR = 'ERROR',
}